---
- name: Larning veriable precedence
  hosts: all
  become: yes

  tasks:

    - debug:
        msg: "username : {{USRNM}} Groupname : {{GRPNM}}"

    - name: Add user
      user:
        name: "{{USRNM}}"
        state: present
        shell: /bin/bash
    - name: Add group 
      group:
        name: "{{GRPNM}}"
        state: present
