---
- name: setup webiste on web group
  hosts: webserver
  become: yes
  tasks:
    - name: installed apache2
      apt:
        name: apache2  
        state: present

    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: push website file
      copy:
        src: index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'

- name: setup mysql on db server
  hosts: dbserver
  become: yes
  tasks:
    - name: install mysql-python
      apt:
        name: mysql-server
        state: present

    - name: start and enable mysql-server
      service:
        name: mysql
        state: started
        enabled: yes

    - name: install mysql-python
      apt:
        name: python3-mysqldb
        state: present

          
    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: bobdata
        state: present

    - name: Create database user with name 'bob' and password '12345' with all database privileges
      mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present

