- name: Common tool setup on all the servers
  hosts: websrvgrp
  become: yes
  vars:
    tom_url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
    tom_home: /usr/local/tomcat8
    tom_download_path: /tmp/tomcat-8.tar.gz
    jdk_cent_ver: java-1.8.0-openjdk.x86_64
    jdk_ubuntu_ver: openjdk-8-jdk
    tom_sys_user: tomcat
    tom_sys_grp: tomcat
    tomcat_user: tomcat
    tomcat_pass: admin123
  tasks:
    - name: Install JDK on Centos 6/7
      yum:
        name: "{{jdk_cent_ver}}"
        state: present
      when: ansible_distribution == 'CentOS'
    
    - name: Install JDK on Ubuntu 14/15/16
      apt:
        name: "{{jdk_ubuntu_ver}}"
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
    
    - name: Download Tomcat Tar Ball/Binaries
      get_url:
        url: "{{tom_url}}"
        dest: "{{tom_download_path}}"
    
    - name: Add tomcat group
      group:
        name: "{{tom_sys_grp}}"
        state: present
    
    - name: Add tomcat user
      user:
        name: "{{tom_sys_user}}"
        group: "{{tom_sys_grp}}"
        shell: /bin/nologin
        home: "{{tom_home}}"
    
    - file:
        path: /tmp/tomcat8
        state: directory
    
    - name: Extract tomcat
      unarchive:
        src: "{{tom_download_path}}"
        dest: /tmp/tomcat8/
        remote_src: yes
        list_files: yes
      register: unarchive_info
    
    - debug:
        msg: "{{unarchive_info.files[0].split('/')[0]}}"
    
    - name: Synchronize /tmp/tomcat8/tomcat_cont /usr/local/tomcat8.
      synchronize:
        src: "/tmp/tomcat8/{{unarchive_info.files[0].split('/')[0]}}/"
        dest: "{{tom_home}}"
      delegate_to: "{{ inventory_hostname }}"
    
    - name: Change ownership of /usr/local/tomcat8
      file:
        path: "{{tom_home}}"
        owner: "{{tom_sys_user}}"
        group: "{{tom_sys_grp}}"
        recurse: yes
    
    - name: Setup tomcat SVC file on Centos 7
      template:
         src: tomcat7-svcfile.j2
         dest: /etc/systemd/system/tomcat.service
         mode: "a+x"
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
    
    - name: Setup tomcat SVC file on Centos 6
      template:
         src: tomcat6-svcfile.j2
         dest: /etc/init.d/tomcat
         mode: "a+x"
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
    
    - name: Setup tomcat SVC file on ubuntu 14/15
      template:
         src: tomcat14_15-svcfile.j2
         dest: /etc/init.d/tomcat
         mode: "a+x"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '16'
    
    - name: Setup tomcat SVC file on ubuntu 16
      template:
         src: tomcat16-svcfile.j2
         dest: /etc/systemd/system/tomcat.service
         mode: "a+x"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'
    
    - name: Reload tomcat svc config in ubuntu 14/15
      command: update-rc.d tomcat defaults
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '16'
    
    - name: Reload tomcat svc config in Centos 6
      command: chkconfig --add tomcat
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
    
    - name: just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes
      when: ansible_distribution_major_version > '6' or ansible_distribution_major_version > '15'
    
    - name: Start & Enable TOmcat 8
      service:
        name: tomcat
        state: started
        enabled: yes
    
    - name: Deploy tomcat user conf
      template:
       src: tomcat-users_xml.j2
       dest: "{{tom_home}}/conf/tomcat-users.xml"
       owner: "{{tom_sys_user}}"
       group: "{{tom_sys_grp}}"
      notify:
        - Restart Tomcat
    
    - name: Deploy context.xml conf
      template:
       src: context_xml.j2
       dest: "{{tom_home}}/webapps/manager/META-INF/context.xml"
       owner: "{{tom_sys_user}}"
       group: "{{tom_sys_grp}}"
      notify:
        - Restart Tomcat
    handlers:
      - name: Restart Tomcat
        service:
          name: tomcat
          state: restarted 
