---
- name: Install Apache Tomcat10 using ansible
  hosts: all
  remote_user: ubuntu
  become: true
  vars:
    TOMCAT_HOME: /opt/tomcat
    DOWNNLOAD_URL: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.21/bin/apache-tomcat-10.0.21.tar.gz
    JAVA_PATH: /usr/lib/jvm/java-1.11.0-openjdk-amd64
  tasks:
    #  - name: Update the System Packages
    # apt:
    #   upgrade: yes
    #   update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

          #  - name: Install JAVA
          #apt:
          #name: default-jdk
          #state: present


    - name: Create a Tomcat Directory
      file:
        path: "{{ TOMCAT_HOME }}"
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
    - name: download tomcat tomcat-10.0.21.tar.gz
      get_url: 
        url: "{{ DOWNNLOAD_URL }}"
        dest: /opt/tomcat/tomcat-10.0.21.tar.gz 

    - name: unarchive tomcat10 
      unarchive:
        src: /opt/tomcat/tomcat-10.0.21.tar.gz
        dest: "{{ TOMCAT_HOME }}"
        remote_src: yes
      register: unarchive_var

    - name: deleter tar file
      file: 
        path: /opt/tomcat/tomcat-10.0.21.tar.gz
        state: absent
      when: unarchive_var.changed
    

    - name: Change ownership of tomcat directory
      file:
        path: "{{ TOMCAT_HOME }}"
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory


    - name: Copy Tomcat service from local to remote
      copy:
        src: templates/tomcat_service.j2
        dest: /etc/systemd/system/tomcat.service
        mode: 0755

    - name: Synchronize /opt/tomcat/apache-tomcat-10.0.21/  /opt/tomcat.
      synchronize:
        src: /opt/tomcat/apache-tomcat-10.0.21/
        dest: "{{ TOMCAT_HOME }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
﻿
