---
- name: setup webiste on web group
  hosts: webserver
  become: yes
  tasks:
    - name: print motd contend
      command: cat /etc/motd
      register: banner

    - debug:
        msg: "content : {{banner.stdout}}"

